### PR TITLE
Add shield example

### PR DESCRIPTION
**Pull request by ishotjr**

### CODE REVIEW

**Review by casundra — APPROVED** [review]
Looks good to me!

**Review by casundra — CHANGES_REQUESTED** [review]
Oh wait!  Do we want the name to be generic like it is (kind of indicating it's an example for any shield), or should we name it something to do with music?  Or Music_Shield?  Just so it's easy for people to find it in the examples, I'm thinking.

**Comment by ishotjr** [comment]
@casundra renamed! 📛 ✏️ :bowtie:

**Review by casundra — APPROVED** [review]
Woo-hoo!  All looks good.

**Pull request merged**
